### ISSUE TITLE
install 显示http://udc-npm.100tal.com/@babel%2fcore\" returned a 403

### ISSUE THREAD

**Issue by speak44** [shfshanyue/2019-ncov#15]
这个包react-dev-utils装不上，报403

**Comment by speak44** [comment]
Error: Cannot find module 'react-dev-utils/chalk'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/chensi/workspace/2019-ncov/scripts/start.js:19:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by shfshanyue** [comment]
使用淘宝的源吧
